name: Build & Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. Login to Docker Hub using secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 2. Get the next version tag
      - name: Set up Image Tag
        id: meta
        run: |
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          echo "tags=netrebnic/web-app:${SHORT_SHA},netrebnic/web-app:latest" >> $GITHUB_OUTPUT

      # 3. Build and Push the Docker Image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64
